blank_issues_enabled: false
contact_links:
  - name: GitHub Community Forum
    url: https://github.community/
    about: Ask questions and discuss the roadmap here.
  - name: GitHub Feedback
    url: https://github.com/github/feedback/discussions
    about: Share your feedback with the GitHub team.
